---
title: "YouTubeProject"
author: "Arthur Lustosa de Souza"
date: "2 de abril de 2017"
output: html_document
---

```{r setup, include=FALSE}
#instalando pacote do youtube 
#install.packages("tuber")
#versao mais atualizada do pacote do youtube
install.packages('devtools')
library(devtools)
devtools::install_github("soodoku/tuber", build_vignettes = TRUE)

#carregando bibliotecas necess?rias
library(tuber)
```

```{r, echo=F}
#autenticando com youtube 
yt_oauth(app_id = "75896210182-3rmjt1ejj59q3hf51dakpd41pn1mdv8e.apps.googleusercontent.com",
        app_secret = "E9UO47eqk_21CkUfJcRJu3fB")
```

```{r}
#carregando biblitotecas extras
library(dplyr) 
library(tibble)
library(lubridate)
library(purrr)
library(ggplot2)
library(tidyr)
```


```{r}

# JoutJout: "UCbE7YGLZ-VY0oCgIsCSJ5Sg"

# LadyGaga_VEVO: "UC07Kxew-cMIaykMOkzqHtBQ" Start: 2009
# Beyonce_VEVO: "UC9zX2xZIJ4cnwRsgBpHGvMg" Start: 2009
# Rihanna_VEVO: "UC2xskkQVFEpLcGFnNSLQY0A" Start: 2009
# KatyPerry_VEVO: "UC-8Q-hLdECwQmaWNwXitYDw" Start: 2008
# BritneySpears_VEVO: "UCZijND2e2tPp2AQL8Go2YSg" Start: 2009
# Madonna_VEVO:"UCmQmc-Y4N9btVMUS1BfnyDw" Start: 2012
# Adele_VEVO: "UComP_epzeKzvBX156r6pm1Q" Start: 2009
# TaylorSwift_VEVO: "UCANLZYMidaCbLQFWXBC95Jg"
# DomiLovato_VEVO: "UCnyB9MYKRkSFK3IIB32CoVw"
# ArianaGrande_VEVO: "UC0VOyT2OCBKdQhF3BAbZ-1g"

get_videos <- function(dates, id_channel) {
  
  yt_search(term = "", 
            type = "video",
            channel_id = id_channel,
            published_after = dates$start,
            published_before = dates$end)
  
}



dates <- tibble(start = seq(ymd("2008-01-01"), ymd("2017-01-01"), by = "years"),
                        end = seq(ymd("2008-12-31"), ymd("2017-12-31"), by = "years")) %>% 
  mutate(start = paste(start, "T0:00:00Z", sep = ""),
         end = paste(end, "T0:00:00Z", sep = ""))

videos_gaga <- by_row(.d = dates, "UC07Kxew-cMIaykMOkzqHtBQ", ..f = get_videos, .to = "videos_info")
videos_beyonce <- by_row(.d = dates, "UC9zX2xZIJ4cnwRsgBpHGvMg", ..f = get_videos, .to = "videos_info")
videos_rihanna <- by_row(.d = dates, "UC2xskkQVFEpLcGFnNSLQY0A", ..f = get_videos, .to = "videos_info")
videos_katyPerry <- by_row(.d = dates, "UC-8Q-hLdECwQmaWNwXitYDw", ..f = get_videos, .to = "videos_info")
videos_britney <- by_row(.d = dates, "UCZijND2e2tPp2AQL8Go2YSg", ..f = get_videos, .to = "videos_info")
videos_madonna <- by_row(.d = dates, "UCmQmc-Y4N9btVMUS1BfnyDw", ..f = get_videos, .to = "videos_info")
videos_adele <- by_row(.d = dates, "UComP_epzeKzvBX156r6pm1Q", ..f = get_videos, .to = "videos_info")
videos_taylor <- by_row(.d = dates, "UCANLZYMidaCbLQFWXBC95Jg", ..f = get_videos, .to = "videos_info")
videos_demi <- by_row(.d = dates, "UCnyB9MYKRkSFK3IIB32CoVw", ..f = get_videos, .to = "videos_info")
videos_ariana <- by_row(.d = dates, "UC0VOyT2OCBKdQhF3BAbZ-1g", ..f = get_videos, .to = "videos_info")
```


```{r}
#pegando estatísticas dos v?deos
get_videos_stats <- function(df_row) {
  get_stats(video_id = df_row$video_id)
}

dados_gaga <- bind_rows(videos_gaga$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_beyonce <- bind_rows(videos_beyonce$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_rihanna <- bind_rows(videos_rihanna$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_katty <- bind_rows(videos_katyPerry$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_britney <- bind_rows(videos_britney$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_madonna <- bind_rows(videos_madonna$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_adele <- bind_rows(videos_adele$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_taylor <- bind_rows(videos_taylor$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_demi <- bind_rows(videos_demi$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")

dados_ariana <- bind_rows(videos_ariana$videos_info) %>% 
  select(title, publishedAt, video_id) %>%
  by_row(..f = get_videos_stats, .to = "videos_stats")
```


```{r}
#gerando visualiza??es
#numero de views
dados_rihanna %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views) %>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt)) %>% 
  ggplot(aes(x = publishedAt, y = views)) +
  geom_line(aes(y = 100000000, colour = "10 Milhão")) +
  geom_line(aes(y = 5000000, colour = "5 Milhão")) +
  geom_line() +
  labs(x = "Data de publiçãoo", y = "Visualizações") +
  theme_bw()

```


```{r}
#numero de likes vs dislikes
dados_gaga %>% 
  mutate(likes = map(videos_stats, .f = 'likeCount'),
         dislikes = map(videos_stats, .f = 'dislikeCount'),
         comments = map(videos_stats, .f = 'commentCount')) %>% 
  unnest(likes, dislikes, comments) %>% 
  mutate(likes = as.numeric(likes),
         dislikes = as.numeric(dislikes),
         comments = as.numeric(comments),
         publishedAt = as_date(publishedAt),
         prop = likes/dislikes) %>% 
  ggplot(aes(x = publishedAt)) +
  geom_line(aes(y = comments, colour = "Likes/Dislikes")) +
  labs(x = "Data de publição", y = "Likes/Dislikes") +
  theme_bw()
```

```{r}
#numero de likes vs dislikes
dados_gaga %>% 
  mutate(comments = map(videos_stats, .f = 'commentCount')) %>% 
  unnest(comments) %>% 
  mutate(comments = as.numeric(comments),
         publishedAt = as_date(publishedAt)) %>% 
  ggplot(aes(x = publishedAt)) +
  geom_line(aes(y = comments, colour = "Comments")) +
  labs(x = "Data de publição", y = "Comments") +
  theme_bw()
```

```{r}
#utilizando Plotly
library(plotly)
packageVersion('plotly')

gaga <- dados_gaga %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Lady Gaga')

beyonce <- dados_beyonce %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Beyonce')


rihanna <- dados_rihanna %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Rihanna')

kattyPerry <- dados_katty %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Katty Perry')

brineySpears <- dados_britney %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Briney Spears')

madonna <- dados_madonna %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Madonna')

adele <- dados_adele %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Adele')

taylor <- dados_taylor %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Taylor Swift')

demi <- dados_demi %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Demi Lovato')

ariana <- dados_ariana %>% 
  mutate(views = map(videos_stats, .f = 'viewCount')) %>% 
  unnest(views )%>% 
  mutate(views = as.numeric(views),
         publishedAt = as_date(publishedAt),
         Nome = 'Ariana Grande')

divas_pop <- rbind(gaga, rihanna, beyonce, kattyPerry, brineySpears, madonna, adele, taylor, demi, ariana)

#divas_pop <- divas_pop %>%
#  select(Nome, title, publishedAt, video_id, views)
#write.csv(divas_pop, "divas_pop.csv", row.names = F)


resume_divas_pop <-  divas_pop %>%
  unnest(views) %>% 
  mutate(views = as.numeric(views),
         ano =  as.numeric( format( as.Date( publishedAt, origin='1900-1-1'), '%Y')),
         publishedAt = as_date(publishedAt)) %>% 
  group_by(Nome, ano) %>%
  summarise(total_views = sum(views)) %>%
  mutate(ano = as.character(ano))
  
  
  
  
ggplot(resume_divas_pop, aes(x = ano, y = total_views, group = Nome, colour = Nome)) +
  geom_line() +
  geom_point() +
  geom_path(alpha = 0.5) +
  labs(x = "Ano", y = "Número de Views") +
  theme_bw()


divas_line_chart <- plot_ly(resume_divas_pop, x = ano, y = total_views, name = 'views', type = 'line', group = Nome,  mode = 'line',  text = paste("Diva: ", Nome))  %>%
  layout(title = "Resumo Divas Pop - Nº views no YouTube por Ano", 
         xaxis = list(title="Ano"),
         yaxis = list(title="Nº de Views"))

divas_line_chart


divas_bouble_chart <- plot_ly(resume_divas_pop, x = ano, y = total_views, size = total_views, group = Nome,  mode = 'markers', text = paste("Diva: ", Nome))  %>%
  layout(title = "Resumo Divas Pop - Nº views no YouTube por Ano", 
         xaxis = list(title="Ano"),
         yaxis = list(title="Nº de Views"))

divas_bouble_chart
```

